name: CI
on:
  workflow_call:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - v2
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    steps:
      # Check out, and set up the node/ruby infra
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      # Install, should be basically instant if cached
      - run: yarn install
        env:
          YARN_CHECKSUM_BEHAVIOR: ignore

      # Verify dependencies are hooked up right
      - run: node test/verifyPackageVersions.js

      # Grab localizations
      - run: yarn docs-sync pull microsoft/TypeScript-Website-localizations#main 1

      # Build the packages
      - run: yarn bootstrap
      - run: yarn build

      # Verify it compiles
      - run: yarn build-site
      - run: cp -r packages/typescriptlang-org/public site

      # Run all the package's tests
      - run: yarn test
        env:
          CI: true

  windows:
    if: github.event.action != 'closed'
    runs-on: windows-latest

    steps:
      # Check out, and set up the node infra
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      # Get local dependencies
      - run: yarn install
        env:
          YARN_CHECKSUM_BEHAVIOR: ignore

      - run: yarn bootstrap
      - run: yarn build
