name: CI
on:
  workflow_call:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - v2
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    steps:
      # Check out, and set up the node/ruby infra
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: yarn

      # Install, should be basically instant if cached
      - run: yarn install
        env:
          YARN_CHECKSUM_BEHAVIOR: ignore

      # Verify dependencies are hooked up right
      - run: node test/verifyPackageVersions.js

      # Grab localizations
      - run: yarn docs-sync pull microsoft/TypeScript-Website-localizations#main 1

      # Build the packages
      - run: yarn bootstrap
      - run: yarn build

      # Verify it compiles
      - run: yarn build-site
      - run: cp -r packages/typescriptlang-org/public site

      # Run all the package's tests
      - run: yarn test
        env:
          CI: true

  deploy-documentation:
    needs: tests
    name: Deploy Documentation to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Build documentation
        run: |
          yarn install
          yarn bootstrap
          yarn build
          yarn build-site
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/typescriptlang-org/public
          user_name: QubitPi
          user_email: jack20191124@proton.me

  windows:
    if: github.event.action != 'closed'
    runs-on: windows-latest

    steps:
      # Check out, and set up the node infra
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: yarn

      # Get local dependencies
      - run: yarn install
        env:
          YARN_CHECKSUM_BEHAVIOR: ignore

      - run: yarn bootstrap
      - run: yarn build
